var namespacecopra =
[
    [ "AutoSpan", "structcopra_1_1AutoSpan.html", "structcopra_1_1AutoSpan" ],
    [ "Constraint", "classcopra_1_1Constraint.html", "classcopra_1_1Constraint" ],
    [ "ControlBoundConstraint", "classcopra_1_1ControlBoundConstraint.html", "classcopra_1_1ControlBoundConstraint" ],
    [ "ControlConstraint", "classcopra_1_1ControlConstraint.html", "classcopra_1_1ControlConstraint" ],
    [ "ControlCost", "classcopra_1_1ControlCost.html", "classcopra_1_1ControlCost" ],
    [ "CostFunction", "classcopra_1_1CostFunction.html", "classcopra_1_1CostFunction" ],
    [ "EqIneqConstraint", "classcopra_1_1EqIneqConstraint.html", "classcopra_1_1EqIneqConstraint" ],
    [ "GUROBISolver", "classcopra_1_1GUROBISolver.html", "classcopra_1_1GUROBISolver" ],
    [ "InitialStateLMPC", "classcopra_1_1InitialStateLMPC.html", "classcopra_1_1InitialStateLMPC" ],
    [ "is_all_arithmetic", "structcopra_1_1is__all__arithmetic.html", null ],
    [ "is_all_arithmetic< std::false_type, T2, T3 >", "structcopra_1_1is__all__arithmetic_3_01std_1_1false__type_00_01T2_00_01T3_01_4.html", null ],
    [ "is_all_arithmetic< std::true_type, std::true_type, std::true_type >", "structcopra_1_1is__all__arithmetic_3_01std_1_1true__type_00_01std_1_1true__type_00_01std_1_1true__type_01_4.html", null ],
    [ "is_all_arithmetic< std::true_type, T2, T3 >", "structcopra_1_1is__all__arithmetic_3_01std_1_1true__type_00_01T2_00_01T3_01_4.html", null ],
    [ "LMPC", "classcopra_1_1LMPC.html", "classcopra_1_1LMPC" ],
    [ "LSSOLSolver", "classcopra_1_1LSSOLSolver.html", "classcopra_1_1LSSOLSolver" ],
    [ "MixedConstraint", "classcopra_1_1MixedConstraint.html", "classcopra_1_1MixedConstraint" ],
    [ "MixedCost", "classcopra_1_1MixedCost.html", "classcopra_1_1MixedCost" ],
    [ "OSQPSolver", "classcopra_1_1OSQPSolver.html", "classcopra_1_1OSQPSolver" ],
    [ "PreviewSystem", "structcopra_1_1PreviewSystem.html", "structcopra_1_1PreviewSystem" ],
    [ "QLDSolver", "classcopra_1_1QLDSolver.html", "classcopra_1_1QLDSolver" ],
    [ "QuadProgDenseSolver", "classcopra_1_1QuadProgDenseSolver.html", "classcopra_1_1QuadProgDenseSolver" ],
    [ "SolverInterface", "classcopra_1_1SolverInterface.html", "classcopra_1_1SolverInterface" ],
    [ "TargetCost", "classcopra_1_1TargetCost.html", "classcopra_1_1TargetCost" ],
    [ "TrajectoryBoundConstraint", "classcopra_1_1TrajectoryBoundConstraint.html", "classcopra_1_1TrajectoryBoundConstraint" ],
    [ "TrajectoryConstraint", "classcopra_1_1TrajectoryConstraint.html", "classcopra_1_1TrajectoryConstraint" ],
    [ "TrajectoryCost", "classcopra_1_1TrajectoryCost.html", "classcopra_1_1TrajectoryCost" ]
];