name: Package copra
on:
  repository_dispatch:
    types:
    - package-master
    - package-release
  push:
    paths-ignore:
    - doc/**
    - README.md
    - ".github/workflows/build.yml"
    branches:
    - "**"
    tags:
    - v*
  pull_request:
    branches:
    - "**"
jobs:
  package:
    uses: jrl-umi3218/github-actions/.github/workflows/package-project.yml@master
    with:
      matrix: |
          {
            "dist": ["bionic", "focal", "jammy"],
            "arch": ["amd64"],
            "include":
            [
              {"dist": "bionic", "arch": "i386" }
            ]
          }
    secrets:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
